<a href="https://colab.research.google.com/github/wujulie/ML__homework/blob/main/homework3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import numpy as np
import pandas as pd
data=pd.read_csv("/content/drive/My Drive/dermatology.csv")
data=pd.DataFrame(data)
print(data.shape)
pd.set_option('display.max_columns',None)#顯示所有列

(366, 35)


In [82]:
print(data)
data.isnull().sum()

     erythema  scaling  definite_borders  itching  koebner_phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
..        ...      ...               ...      ...                 ...   
361         2        1                 1        0                   1   
362         3        2                 1        0                   1   
363         3        2                 2        2                   3   
364         2        1                 3        1                   2   
365         3        2                 2        0                   0   

     polygonal_papules  follicular_papules  oral_mucosal_involvement  \
0                    0                   0         

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee_and_elbow_involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
pnl_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epi

In [83]:
from sklearn.impute import SimpleImputer 
from sklearn import preprocessing
imp = SimpleImputer(strategy="most_frequent")
data["age"] = imp.fit_transform(data[["age"]])
data.isnull().sum()

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee_and_elbow_involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
pnl_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epi

In [84]:
X=data.iloc[:,:-1]
Y=data.iloc[:,-1]
print(X.shape)
print(Y.shape)

(366, 34)
(366,)


In [85]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split,cross_val_score
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.25)
mnb = MultinomialNB(alpha=0.01)
mnb.fit(X_train,Y_train)
print("MultinomialNB score:",mnb.score(X_test,Y_test))


MultinomialNB score: 0.9782608695652174


In [86]:
print("MultinomialNB score cross_val_score:",cross_val_score(mnb,X,Y,scoring='accuracy',cv=10).mean())

MultinomialNB score cross_val_score: 0.9780030030030028


In [87]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true=Y_test,y_pred=lr.predict(X_test))
print(cm)
print("\n")
print(cm.transpose()[::-1,::-1])
print("\n")
print(cm[::-1,::-1])

[[24  0  0  0  0  0]
 [ 0 17  0  0  0  0]
 [ 0  0 19  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  0 12  0]
 [ 0  0  0  0  0  8]]


[[ 8  0  0  0  0  0]
 [ 0 12  0  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0  0  0 17  0]
 [ 0  0  0  0  0 24]]


[[ 8  0  0  0  0  0]
 [ 0 12  0  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  0 19  0  0]
 [ 0  0  0  0 17  0]
 [ 0  0  0  0  0 24]]


In [89]:
from sklearn.metrics import classification_report
target_names = ['class1','class2','class3','class4','class5','class6']
y_true=Y_test
y_pred=lr.predict(X_test)
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

      class1       1.00      1.00      1.00        24
      class2       1.00      1.00      1.00        17
      class3       1.00      1.00      1.00        19
      class4       1.00      1.00      1.00        12
      class5       1.00      1.00      1.00        12
      class6       1.00      1.00      1.00         8

    accuracy                           1.00        92
   macro avg       1.00      1.00      1.00        92
weighted avg       1.00      1.00      1.00        92



In [90]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LogisticRegression
# Split dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.25)
# Create logistic regressor
lr = LogisticRegression()
lr.fit(X_train, Y_train)
print('Logistic regression score: %.3f' % lr.score(X_test,Y_test))


Logistic regression score: 0.989


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [91]:
print("Logistic regression cross_val_score:",cross_val_score(lr,X,Y,scoring='accuracy',cv=10).mean())

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Logistic regression cross_val_score: 0.9698948948948949


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [92]:
print(lr.intercept_)

[-0.36763033 -0.44382243 -0.24579933  0.70332364  0.05772872  0.29619973]


In [93]:
print(lr.coef_)


[[-7.03353154e-03  1.18834746e-01  2.39293959e-01 -1.32236355e-01
   9.95975109e-02 -7.68172854e-02 -2.42378273e-01 -5.95249359e-02
   4.42474026e-01  3.79816331e-01  2.13184857e-02 -6.73305541e-02
  -5.82488406e-02  4.67193411e-01 -4.04645365e-01 -4.45600993e-01
  -2.26183125e-01 -2.02066983e-02  1.73953564e-01  7.95901968e-01
   6.22358188e-01  9.15153511e-01  4.04311692e-01  3.66805219e-01
  -6.28932102e-02  2.38306123e-01 -7.25011523e-02 -7.07182779e-01
  -1.26137086e-01 -1.60510748e-01 -1.63747259e-01 -8.08944465e-02
  -7.41790604e-02  3.08656582e-02]
 [ 1.59745317e-01  5.16954628e-01 -2.04141084e-02  4.31609689e-01
  -8.70526721e-01 -1.79345329e-01 -3.68319227e-01 -8.50752069e-02
  -8.64114450e-02 -1.06428481e-01 -4.43475973e-03 -1.31346673e-01
   5.30267729e-01  9.33965452e-01 -4.76009655e-01  3.93736869e-01
   5.63883097e-02 -3.86917641e-01 -3.85854857e-01 -3.32396092e-01
  -3.74885846e-01 -3.16959155e-01  7.67507810e-03 -1.02160226e-01
  -1.48261391e-01 -1.29389508e+00 -1.7291

In [94]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss='log', max_iter=1000)
sgd.fit(X_train, Y_train)
print("SGDClassifier score:",sgd.score(X_test, Y_test))
print("SGDClassifier cross_val_score:",cross_val_score(sgd,X,Y,scoring='accuracy',cv=10).mean())

SGDClassifier score: 0.8695652173913043
SGDClassifier cross_val_score: 0.8844594594594597


In [95]:
from sklearn.linear_model import Perceptron
perc=Perceptron(tol=1e-3, random_state=0)
perc.fit(X_train, Y_train)
print("Perceptron score:",perc.score(X_test,Y_test))
print("Perceptron cross_val_score:",cross_val_score(perc,X,Y,scoring='accuracy',cv=10).mean())

Perceptron score: 0.8478260869565217
Perceptron cross_val_score: 0.9012012012012012


In [96]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train, Y_train)
print("BernoulliNB score:",bnb.score(X_test, Y_test))
print("BernoulliNB cross_val_score:",cross_val_score(bnb,X,Y,scoring='accuracy',cv=10).mean())

BernoulliNB score: 0.9891304347826086
BernoulliNB cross_val_score: 0.9781531531531531


In [97]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
nb_samples = 366
X, Y = make_classification(n_samples=nb_samples, n_features=34, n_informative=2, n_redundant=0)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
print("GaussianNB score:",gnb.score(X_test, Y_test))
print("GaussianNB cross_val_score:",cross_val_score(gnb,X,Y,scoring='accuracy',cv=10).mean())


GaussianNB score: 0.8804347826086957
GaussianNB cross_val_score: 0.8527777777777779


In [98]:
Y_gnb_score = gnb.predict_proba(X_test)
Y_lr_score = lr.predict_proba(X_test)
from sklearn.metrics import roc_curve, auc
fpr_gnb, tpr_gnb, thresholds_gnb = roc_curve(Y_test, Y_gnb_score[:, 1])
fpr_lr, tpr_lr, thresholds_lr = roc_curve(Y_test, Y_lr_score[:,1])
auc(fpr_gnb, tpr_gnb)
auc(fpr_lr, tpr_lr)

0.5309692671394799

In [99]:
from sklearn.model_selection import GridSearchCV
param_grid = [{'penalty': [ 'l1', 'l2' ],'C': [ 0.5, 1.0, 1.5, 1.8, 2.0, 2.5]}]
gs = GridSearchCV(estimator=LogisticRegression(), param_grid=param_grid, scoring='accuracy', cv=10)
gs.fit(X_train,Y_train)
gs.best_estimator_
print("GridSearchCV score:",gs.score(X_test,Y_test))
print("GridSearchCV cross_val_score:",cross_val_score(gs.best_estimator_, X_test, Y_test, scoring='accuracy', cv=10).mean())


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_se

GridSearchCV score: 0.8260869565217391
GridSearchCV cross_val_score: 0.8566666666666667


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)


In [100]:
Y_test_result=np.array(Y_test)
print(Y_test_result)

[0 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 0 0 0 1 0 1
 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 0 1 1 0
 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1]


In [101]:
print(lr.predict(X_test))

[4 2 5 4 2 4 1 2 1 4 4 6 6 4 2 5 4 1 4 4 1 3 5 5 2 4 2 4 4 2 4 2 5 5 4 1 2
 2 5 4 2 2 4 6 3 2 6 4 2 1 4 5 1 2 1 4 4 2 6 5 2 5 5 2 1 5 6 5 2 1 4 4 2 6
 4 4 4 1 4 4 6 5 2 2 4 4 1 1 4 5 4 2]
